# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_initialize_logLikFn <- function(dv, dm, dm_ncoef, constraints, data, cnames) {
    .Call('satf_rcpp_initialize_logLikFn', PACKAGE = 'satf', dv, dm, dm_ncoef, constraints, data, cnames)
}

rcpp_update_constraints_logLikFn <- function(constraints) {
    .Call('satf_rcpp_update_constraints_logLikFn', PACKAGE = 'satf', constraints)
}

rcpp_deinitialize_logLikFn <- function() {
    .Call('satf_rcpp_deinitialize_logLikFn', PACKAGE = 'satf')
}

rcpp_is_initialized_logLikFn <- function() {
    .Call('satf_rcpp_is_initialized_logLikFn', PACKAGE = 'satf')
}

rcpp_get_coef_names <- function() {
    .Call('satf_rcpp_get_coef_names', PACKAGE = 'satf')
}

rcpp_compute_logLikFn <- function(coefs, by_row = FALSE, tolerate_imprecision = TRUE, force_update = FALSE) {
    .Call('satf_rcpp_compute_logLikFn', PACKAGE = 'satf', coefs, by_row, tolerate_imprecision, force_update)
}

rcpp_compute_logLikFn_gradient <- function(coefs, by_row = FALSE, tolerate_imprecision = TRUE) {
    .Call('satf_rcpp_compute_logLikFn_gradient', PACKAGE = 'satf', coefs, by_row, tolerate_imprecision)
}

rcpp_constrain_coefs <- function(coefs) {
    .Call('satf_rcpp_constrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_unconstrain_coefs <- function(coefs) {
    .Call('satf_rcpp_unconstrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_select_coef_subset <- function(coefnames) {
    .Call('satf_rcpp_select_coef_subset', PACKAGE = 'satf', coefnames)
}

rcpp_reset_selection <- function() {
    invisible(.Call('satf_rcpp_reset_selection', PACKAGE = 'satf'))
}

rcpp_return_selection <- function() {
    .Call('satf_rcpp_return_selection', PACKAGE = 'satf')
}

rcpp_set_coef_values <- function(values) {
    invisible(.Call('satf_rcpp_set_coef_values', PACKAGE = 'satf', values))
}

rcpp_reset_coef_ranges <- function(names) {
    invisible(.Call('satf_rcpp_reset_coef_ranges', PACKAGE = 'satf', names))
}

rcpp_pnorm2d <- function(x_lower, y_lower, rho, second_order) {
    .Call('satf_rcpp_pnorm2d', PACKAGE = 'satf', x_lower, y_lower, rho, second_order)
}

rcpp_pnorm2d_derivative_by_rho <- function(a, b, rho, second_order) {
    .Call('satf_rcpp_pnorm2d_derivative_by_rho', PACKAGE = 'satf', a, b, rho, second_order)
}

rcpp_correlate <- function(trial_id, noise, rho_vec) {
    .Call('satf_rcpp_correlate', PACKAGE = 'satf', trial_id, noise, rho_vec)
}

