library(sets)
library(plyr)
library(Rcpp)
library(maxLik)
library(nloptr)
source("Z:/Downloads/satf-master/repos/satf/R/satf_misc.R")
source("Z:/Downloads/satf-master/repos/satf/R/satf_aggregate.R")
source("Z:/Downloads/satf-master/repos/satf/R/satf_params.R")
source("Z:/Downloads/satf-master/repos/satf/R/satf_generate.R")
source("Z:/Downloads/satf-master/repos/satf/R/satf_resample.R")
source("Z:/Downloads/satf-master/repos/satf/R/satf.R")
Rcpp::sourceCpp("Z:/Downloads/satf-master/repos/satf/test/satf_load.cpp", rebuild=T)